name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
        env:
          - bun
          - jest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # setup-bun currently not working with Windows
      # For MacOS and Linux only
      - uses: oven-sh/setup-bun@v1
        if: ${{ matrix.env == 'bun' && runner.os != 'Windows' }}
      - run: |
          # WARNING: No stability is guaranteed on the experimental Windows builds
          powershell -c "irm bun.sh/install.ps1|iex"
          setx /M PATH "C:\Users\runneradmin\.bun\bin\;%PATH%"
        if: ${{ matrix.env == 'bun' && runner.os == 'Windows' }}
      - run: |
          bun -v
          bun install
          bun install --no-save esbuild@^0.19.11
          bun test --coverage
        if: ${{ matrix.env == 'bun' }}

      - run: |
          node -v && npm -v
          npm i
          npm i --no-save jest esbuild@^0.19.11
          # https://jestjs.io/docs/ecmascript-modules
          node --experimental-vm-modules node_modules/jest/bin/jest --coverage
        if: ${{ matrix.env == 'jest' }}
